---
openapi: 3.0.0
info:
  version: 1.0.0
  title: API
  description: ''
  termsOfService: ''
  contact:
    name: ''
  license:
    name: ''
servers:
- url: http://localhost
paths:
  "/users":
    get:
      operationId: list_users
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
components:
  schemas:
    user:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
      required:
      - first_name
      - last_name
